apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serving
  namespace: argocd
spec:
  destination:
    namespace: mlops
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/example/mlops-drift-platform.git
    path: manifests/k8s/overlays/prod
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
