name: nightly-drift

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install poetry && poetry install --only main
      - name: Run Evidently drift job
        run: poetry run python services/monitoring/drift/run_evidently.py
      - name: Upload drift report
        uses: actions/upload-artifact@v4
        with:
          name: drift-report
          path: services/monitoring/drift/reports/latest.html
